### ISSUE TITLE
Cannot find manipulator for ODTQueryReverseStepImpl

### ISSUE THREAD

**Issue by timmisset** [timmisset/omt-odt-plugin#223]
com.intellij.diagnostic.PluginException: Cannot find manipulator for ODTQueryReverseStepImpl(QUERY_REVERSE_STEP) in com.misset.opp.odt.psi.reference.ODTTTLSubjectPredicateReference(ODTQueryReverseStepImpl(QUERY_REVERSE_STEP):null) class class com.misset.opp.odt.psi.reference.ODTTTLSubjectPredicateReference [Plugin: com.misset.OMT]
    at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
    at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:83)

**Comment by timmisset** [comment]
Cannot reproduce
